name: Simple iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build IPA
      run: |
        cd ios_app
        
        # Clean build folder
        rm -rf build/
        mkdir -p build/
        
        # Build for iOS device
        xcodebuild -project EmployeeManagementApp.xcodeproj \
          -scheme EmployeeManagementApp \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath build/EmployeeManagementApp.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
        # Export IPA
        xcodebuild -exportArchive \
          -archivePath build/EmployeeManagementApp.xcarchive \
          -exportPath build/ \
          -exportOptionsPlist ExportOptions.plist \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
        # List build artifacts
        ls -la build/
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: EmployeeManagementApp.ipa
        path: ios_app/build/EmployeeManagementApp.ipa
        retention-days: 30
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: build-${{ github.run_number }}
        release_name: Build ${{ github.run_number }}
        body: |
          ## Build Information
          - **Commit**: ${{ github.sha }}
          - **Branch**: ${{ github.ref_name }}
          - **Triggered by**: ${{ github.actor }}
          - **Date**: ${{ github.event.head_commit.timestamp }}
          
          ## Download
          Tải file IPA từ phần Artifacts bên dưới.
          
          ## Installation
          1. Tải file IPA
          2. Cài đặt qua Xcode hoặc Cydia Impactor
          3. Trust developer certificate trong Settings
        draft: false
        prerelease: true
