# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'EmployeeManagementApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmployeeManagementApp
  # Add any third-party dependencies here
  
  # Example pods (uncomment if needed):
  # pod 'Alamofire', '~> 5.0'
  # pod 'SwiftyJSON', '~> 5.0'
  # pod 'KeychainAccess', '~> 4.0'
  # pod 'CryptoSwift', '~> 1.0'

  target 'EmployeeManagementAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmployeeManagementAppUITests' do
    # Pods for testing
  end

end

