name: platformnext_vpn
description: Platform Next - Unlimited VPN Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  circle_flags: ^2.0.0
  flex_color_picker: ^3.6.0
  fluentui_system_icons: ^1.1.0
  iconsax_flutter: ^1.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Network & HTTP
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  cupertino_http: ^0.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  mmkv: ^2.0.0
  
  # Device & System
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  flutter_timezone: ^0.9.2
  
  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  
  # QR Code
  qr_code_scanner: ^1.0.1
  qr_code_scanner_plus: ^0.0.6
  
  # Barcode Scanner
  mtbbarcode_scanner: ^0.0.6
  
  # Image Processing
  sdwebimage: ^0.0.1
  swifty_gif: ^0.0.1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  
  # Monitoring
  sentry_flutter: ^7.14.0
  
  # In-App Purchase
  in_app_purchase: ^3.1.11
  in_app_review: ^2.0.9
  
  # Permissions
  permission_handler: ^11.2.0
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Protocol Handler
  protocol_handler: ^0.0.1
  
  # Keyboard
  flutter_keyboard_visibility: ^5.4.0
  
  # Splash Screen
  flutter_native_splash: ^2.3.7
  
  # Network Info
  network_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/connection/
    - assets/core/
    - assets/custom/
    - assets/flags/
    - assets/fonts/
    - assets/images/
  
  fonts:
    - family: Emoji
      fonts:
        - asset: assets/fonts/Emoji.ttf
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.otf
    - family: CupertinoIcons
      fonts:
        - asset: packages/cupertino_icons/assets/CupertinoIcons.ttf
    - family: FluentSystemIcons
      fonts:
        - asset: packages/fluentui_system_icons/fonts/FluentSystemIcons-Regular.ttf
        - asset: packages/fluentui_system_icons/fonts/FluentSystemIcons-Filled.ttf
    - family: FlutterIconsax
      fonts:
        - asset: packages/iconsax_flutter/fonts/FlutterIconsax.ttf
